package com.fyeeme.mybatis.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   资讯
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article
 */
public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   资讯标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private String title;

    /**
     * Database Column Remarks:
     *   缩略图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.thumbnail
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private String thumbnail;

    /**
     * Database Column Remarks:
     *   分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.category_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.status
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private String status;

    /**
     * Database Column Remarks:
     *   所属机构ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tenant_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Integer tenantId;

    /**
     * Database Column Remarks:
     *   是否头条
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.featured
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Byte featured;

    /**
     * Database Column Remarks:
     *   资讯浏览次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.view_count
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Integer viewCount;

    /**
     * Database Column Remarks:
     *   发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.published_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Date publishedTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.created_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Date createdTime;

    /**
     * Database Column Remarks:
     *   最后更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updated_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Date updatedTime;

    /**
     * Database Column Remarks:
     *   创建者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.created_by_user_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Integer createdByUserId;

    /**
     * Database Column Remarks:
     *   修改者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.updated_by_user_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private Integer updatedByUserId;

    /**
     * Database Column Remarks:
     *   资讯内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.thumbnail
     *
     * @return the value of article.thumbnail
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.thumbnail
     *
     * @param thumbnail the value for article.thumbnail
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.category_id
     *
     * @return the value of article.category_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.category_id
     *
     * @param categoryId the value for article.category_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.status
     *
     * @return the value of article.status
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.status
     *
     * @param status the value for article.status
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tenant_id
     *
     * @return the value of article.tenant_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tenant_id
     *
     * @param tenantId the value for article.tenant_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.featured
     *
     * @return the value of article.featured
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Byte getFeatured() {
        return featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.featured
     *
     * @param featured the value for article.featured
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setFeatured(Byte featured) {
        this.featured = featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.view_count
     *
     * @return the value of article.view_count
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.view_count
     *
     * @param viewCount the value for article.view_count
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.published_time
     *
     * @return the value of article.published_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Date getPublishedTime() {
        return publishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.published_time
     *
     * @param publishedTime the value for article.published_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setPublishedTime(Date publishedTime) {
        this.publishedTime = publishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.created_time
     *
     * @return the value of article.created_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.created_time
     *
     * @param createdTime the value for article.created_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updated_time
     *
     * @return the value of article.updated_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updated_time
     *
     * @param updatedTime the value for article.updated_time
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.created_by_user_id
     *
     * @return the value of article.created_by_user_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Integer getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.created_by_user_id
     *
     * @param createdByUserId the value for article.created_by_user_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setCreatedByUserId(Integer createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.updated_by_user_id
     *
     * @return the value of article.updated_by_user_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public Integer getUpdatedByUserId() {
        return updatedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.updated_by_user_id
     *
     * @param updatedByUserId the value for article.updated_by_user_id
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setUpdatedByUserId(Integer updatedByUserId) {
        this.updatedByUserId = updatedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Sat Feb 26 22:48:34 CST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }
}